build: Link to libm for fpclassify()
Linking with the gold linker failed with an undefined reference to
__fpclassify since it uses '--no-copy-dt-needed-entries' by default.

Fixes: https://bugs.freedesktop.org/show_bug.cgi?id=62264
Signed-off-by: Richard Hughes <richard@hughsie.com>